<?php

class UserResource extends \Illuminate\Http\Resources\Json\JsonResource
{
    public function toArray($request)
    {
        //return parent::toArray($request); // TODO: Change the autogenerated stub
        return [
          'id'=>$this->id,
          'name'=>$this->name,
            'email'=>$this->email,
        ];
    }
}
